server:
  port: 8085
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
        cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
        generate_statistics: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  logging:
    level:
      root: debug
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
